### ISSUE TITLE
添加了新的代理IP源地址后出现错误。

### ISSUE THREAD

**Issue by leoxzl** [qiyeboy/IPProxyPool#104]
在config.py添加了以下代码:
    {
        'urls': ['http://jav8.cc/ProxyIP.html',
        'type': 'regular',
        'pattern': r'[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{2,5}',
        'position': {'ip': 0, 'port': 1, 'type': -1, 'protocol': 2}
    }

然后运行命令: python IPProxy.py 
出现以下错误:
Traceback (most recent call last):
  File "IPProxy.py", line 4, in <module>
    from api.apiServer import start_api_server
  File "/root/IPProxyPool/api/apiServer.py", line 8, in <module>
    import config
  File "/root/IPProxyPool/config.py", line 100
    'type': 'regular',
          ^
SyntaxError: invalid syntax

请帮忙，谢谢!

**Comment by gwl002** [comment]
语法错误也好意思拿来问，上面那个中括号是什么情况，

**Comment by zerowinning** [comment]
'urls': ['http://jav8.cc/ProxyIP.html'**]**,
少一个中括号
