### ISSUE TITLE
请问是如何处理爬取过程中ip被封的呢？使用已过滤的代理？

### ISSUE THREAD

**Issue by raiseG** [qiyeboy/IPProxyPool#108]
本来是打算自己写的，纠结了好久才发现自己只会复制粘贴 (눈‸눈) 
另 这个代理网站也还行:http://ip.seofangfa.com/ 试了几个都是有效的

**Comment by raiseG** [comment]
没仔细看代码，提出这么无脑的问题，真是抱歉 (눈‸눈)

**Comment by qiyeboy** [comment]
@使用已过滤的代理
