### ISSUE TITLE
我尝试安装了，但是接口查不到数据，数据库也是空的

### ISSUE THREAD

**Issue by mliu111477** [qiyeboy/IPProxyPool#12]
总是会报出：
HTTPConnectionPool(host='123.154.179.204', port=8998): Max retries exceeded with url: http://www.stilllistener.com/checkpoint1/test11/ (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x10be7a110>, 'Connection to 123.154.179.204 timed out. (connect timeout=5)'))

这类的信息。。是因为代理不可以么？可以我运行二十多分钟了，一个代理都没有？？？难道是因为都不可用么？

**Comment by gogoforit** [comment]
同问。。我也是数据库也是空的。。

**Comment by qiyeboy** [comment]
@mliu111477 @gogoforit 多等一段时间，正在改进效率

**Comment by Hacker-One** [comment]
me too. 一直是没有可用的代理IP，数据库一直是空的

**Comment by qiyeboy** [comment]
已经更新了，大家可以使用
