### ISSUE TITLE
抓不到可用数据

### ISSUE THREAD

**Issue by hnyer** [qiyeboy/IPProxyPool#13]
![image](https://cloud.githubusercontent.com/assets/5989755/20958689/c7cdf638-bc91-11e6-8679-3a7887da4d08.png)
![image](https://cloud.githubusercontent.com/assets/5989755/20958701/d922c01c-bc91-11e6-90b1-0be32d4939c1.png)

**Comment by Hacker-One** [comment]
我的也是这个问题，但是我查看了下源码，发现是作者写的那个检测proxytype函数checkProxyType有问题，请求的config.TEST_PROXY好像有问题，作者给你讲一下吗？那个URL怎么无法访问呢？

**Comment by qiyeboy** [comment]
把程序启动一个小时以上，看看是否有数据，我正在改进效率

**Comment by qiyeboy** [comment]
TEST_PROXY现在好像无法访问了，我再找一个 @Hacker-One

**Comment by masiqi** [comment]
嗯，不能访问了

**Comment by qiyeboy** [comment]
有没有可以检测代理高匿的网站呀，实在不行只能把检测高匿给去了 @masiqi

**Comment by sweetpineapple** [comment]
我这两天也爬不到代理，主要是TEST_PROXY访问不了。要不就做成TEST_URL检测就可以

**Comment by qiyeboy** [comment]
已经修改了，等把数据库适配做完就更新 @sweetpineapple

**Comment by qijianjun** [comment]
@qiyeboy 看到更新了，给力！

**Comment by qiyeboy** [comment]
现在对python3正在进行适配，有什么问题及时反馈 @qijianjun
