### ISSUE TITLE
apiServer.py 不能在py3中正常运行

### ISSUE THREAD

**Issue by amwukddx** [qiyeboy/IPProxyPool#135]
**apiServer.py 不能再py3里运行，原因是web没有python3的版本，建议改成flask之类的服务器模块，以下是我的测试效果**
-----------------------
`# coding:utf-8`
`'''`
`定义几个关键字，count type,protocol,country,area,`
`'''`
`import json`
`from db.DataStore import sqlhelper`
`from flask import Flask`
`from flask import request`

`app = Flask(__name__)`
`@app.route('/', methods=['GET', 'POST'])`
`def home():`
`    inputs = request.form`
`    json_result = json.dumps(sqlhelper.select(inputs.get('count', None), inputs))`
`    return json_result`

`@app.route('/delete', methods=['GET', 'POST'])`
`def delete():`
`    inputs = request.form`
`    json_result = json.dumps(sqlhelper.delete(inputs))`
`    return json_result`

`def start_api_server():`
`    app.run(port=8000)`

`if __name__ == '__main__':`
`    app.run(port=8000)`

**Comment by qiyeboy** [comment]
![image](https://user-images.githubusercontent.com/8142734/33704943-5ad6337c-db69-11e7-89b3-8f280f8fbfe6.png)
