### ISSUE TITLE
今天停掉程序重启后，爬了很久一直都是0个

### ISSUE THREAD

**Issue by LeoHirasawa** [qiyeboy/IPProxyPool#136]
只在config里改了几个参数，然后删掉了sqlite文件，重新启动程序就一直为0，会不会是因为检查频率调的太快了（调成了3分钟）导致我自己的ip被代理网站封掉了？还是存在其他问题呢 谢谢

**Comment by CHARLESYAN1** [comment]
66Ip 是不是加了反爬，感觉挂了

**Comment by LeoHirasawa** [comment]
好像是不挂代理就连不上

**Comment by LeoHirasawa** [comment]
感觉作者好像放弃这个项目了..

**Comment by qiyeboy** [comment]
![image](https://user-images.githubusercontent.com/8142734/34327158-5f08e4e8-e8f8-11e7-88d0-17de099b62bc.png)
我一直都能爬取代理ip呀

**Comment by qiyeboy** [comment]
@LeoHirasawa @CHARLESYAN1 @light4 @bladestone01

**Comment by CHARLESYAN1** [comment]
嗯，最近正常了，感觉前几天66IP服务器被攻击了，一直返回503错误，其实这些网站只要稍微改版爬虫就Bug了

**Comment by CHARLESYAN1** [comment]
但还是感谢作者 @qiyeboy 最近2个月基本都没出现过什么问题：）出问题也是IP网站的问题

其实IPPool二级代理是大大的福利
