### ISSUE TITLE
ImportError: No module named web 大佬帮忙看看，感激不尽

### ISSUE THREAD

**Issue by leeyuanzhang** [qiyeboy/IPProxyPool#143]
![c n 6452a aiy9n8r9 67bk](https://user-images.githubusercontent.com/22285205/38413316-e67e5668-39bd-11e8-86b2-803a7173b19e.png)

没有做任何操作，大佬帮忙看看，感激不尽

**Comment by leeyuanzhang** [comment]
pip install web.py

**Comment by yjshi2015** [comment]
一样的问题,环境是Python2.7,安装了web.py,版本是0.38,依旧不行....
