### ISSUE TITLE
util.exception.Con_DB_Fail: <exception str() failed> 急 ，拜谢大佬

### ISSUE THREAD

**Issue by leeyuanzhang** [qiyeboy/IPProxyPool#144]
![n zpl k 6v x7 xz x](https://user-images.githubusercontent.com/22285205/38416527-8fdac59e-39c7-11e8-8230-601ca6090807.png)
![8cha_4h_ hnbp9 r b87](https://user-images.githubusercontent.com/22285205/38416555-a17497d0-39c7-11e8-9f47-720c01a33df7.png)

大佬帮忙看看，拜谢

**Comment by leeyuanzhang** [comment]
@qiyeboy 大佬帮忙看看

**Comment by nthreex** [comment]
这好像是连接数据库失败，你是不是没有安装mysqldb这个模块，或者root用户的密码不是root？
我的现在可以跑了，就是一直Success ip num: 0 。。。。不知道你的怎么样？

**Comment by leeyuanzhang** [comment]
已经解决，依赖环境没有安装全

**Comment by nthreex** [comment]
解决就好，如果你的有爬取到成功的代理麻烦告诉我一下，我的一直是0。。。

**Comment by leeyuanzhang** [comment]
可爬取带的，我已经爬取成功了。。。
不过都是免费代理效果达不到预期，我打算用付费服务了
