### ISSUE TITLE
感觉validator跟查IP的测试网站耦合较强

### ISSUE THREAD

**Issue by qijianjun** [qiyeboy/IPProxyPool#18]
比如我要抓取豆瓣API，比较务实的验证策略就是保证访问某个API地址时，始终返回200，且数据长度比较合理（因为测试地址是固定的，所以正确的数据长度是可预期的），所以我将
`if not r.ok or r.text.find(ip)==-1:`
改为
` if r.status_code != 200 and len(r.text) > 10000:`
本来以为这样就可以了，但运行发现报异常报错，追踪发现校验组件跟一个以固定格式返回IP的网站耦合较强，改起来有些麻烦，所以索性在getMyIp函数输出一个固定值，防止报错。

从代码看，获取本机地址是为了检查代理IP的匿名程度，既然现在暂时未启用这个功能，不妨屏蔽相关代码；并且通常校验代理的可用性是针对想爬取的网站而言的，如果校验组件的运行要求校验地址必须是示例中那种类型的，会削弱校验组件的实用性。

**Comment by qiyeboy** [comment]
嗯呢，说的没错，其实更好地做法是针对指定网址测试IP的可用性，之前考虑过，但是为了方便直接选择了一个固定网址，之后我还是加入一个测试接口吧，过段时间在更新吧，最近有点忙

**Comment by qiyeboy** [comment]
@qijianjun

**Comment by qijianjun** [comment]
@qiyeboy 嗯，目前简单修改下用着也不错，以后再改吧。

**Comment by qiyeboy** [comment]
最好还是检测一下ip是否高匿，之前的检测网站挂掉了
