### ISSUE TITLE
web.py不支持python3？

### ISSUE THREAD

**Issue by qijianjun** [qiyeboy/IPProxyPool#19]
之前只是简单了解过web.py，没深入学习过，在p3安装过程中报错：
>ImportError: No module named 'utils'

查了下有这个帖子，似乎是不支持的？
[python3 ImportError: No module named utils #180
](https://github.com/webpy/webpy/issues/180)
[web.py won't install on python 3 #2
](https://github.com/ananelson/dexy-viewer/issues/2
)

**Comment by qijianjun** [comment]
安装开放版解决了问题

**Comment by eleganceZf** [comment]
怎么装？

**Comment by eleganceZf** [comment]
可以给个教程么?
