### ISSUE TITLE
ip过期问题

### ISSUE THREAD

**Issue by DaoQiu** [qiyeboy/IPProxyPool#20]
请教一个问题哈，由于ip是有时效性的，比如ip过期，有没有机制去清除过期的ip呢？

**Comment by qiyeboy** [comment]
config.py中设置每一个小时检测一次，无效的ip会被删除，有效的ip会加分，当总ip数小于一个最小值时，会从重新抓取，都可以在config.py中设置，尽可能设置的时间不要太短，容易被封
