### ISSUE TITLE
还有一个小建议

### ISSUE THREAD

**Issue by smallevil** [qiyeboy/IPProxyPool#24]
其实对于程序来说,只有两个地区就够了.
国内,国外
在提取IP时,能不能有这个,而不是按国家名,
比如我想要国外的,只要country=国外就OK了.
如果指定国家名,那就太多了.国内写中国倒简单

**Comment by Duanexiao** [comment]
同意，国外那些国家名字都不知道会不会写错，还不知道有哪些国家的IP
