### ISSUE TITLE
python3 运行 一直不动...

### ISSUE THREAD

**Issue by bifeng** [qiyeboy/IPProxyPool#28]
D:\IPProxyPool-master\IPProxyPool_py3>python IPProxy.py
IPProxyPool----->>>>>>>>beginning
IPProxyPool----->>>>>>>>db exists ip:0
IPProxyPool----->>>>>>>>now ip num < MINNUM,start crawling...
http://0.0.0.0:8000/
127.0.0.1:65199 - - [20/Dec/2016 16:19:56] "HTTP/1.1 GET /" - 200 OK
127.0.0.1:65208 - - [20/Dec/2016 16:21:32] "HTTP/1.1 GET /" - 200 OK
127.0.0.1:65218 - - [20/Dec/2016 16:21:32] "HTTP/1.1 GET /" - 200 OK
127.0.0.1:65208 - - [20/Dec/2016 16:21:32] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
127.0.0.1:65208 - - [20/Dec/2016 16:21:33] "HTTP/1.1 GET /favicon.ico" - 404 Not Found

这是什么意思？能解答一下吗？

**Comment by qiyeboy** [comment]
python3版本有问题，近期修改，你可以暂时使用py2版本

**Comment by qiyeboy** [comment]
python3版本有问题，近期修改，你可以暂时使用py2版本

**Comment by qiyeboy** [comment]
py3版本bug已经成功修复 @bifeng

**Comment by bifeng** [comment]
大赞！！！
![image](https://cloud.githubusercontent.com/assets/8215563/21373967/e967766c-c75d-11e6-85b3-1d1a4fd49771.png)

**Comment by bifeng** [comment]
![image](https://cloud.githubusercontent.com/assets/8215563/21373978/fd1442bc-c75d-11e6-8188-89ee02ce5000.png)
