### ISSUE TITLE
python3 一个小时过去了，为什么还是空数据库呢？

### ISSUE THREAD

**Issue by bifeng** [qiyeboy/IPProxyPool#29]
只安装了pymysql, 没有安装sqlite.
难道没有写入mysql数据库吗？
----------------------------------------------
D:\IPProxyPool-master\IPProxyPool_py3>python IPProxy.py
IPProxyPool----->>>>>>>>beginning
IPProxyPool----->>>>>>>>db exists ip:0
IPProxyPool----->>>>>>>>now ip num < MINNUM,start crawling...
http://0.0.0.0:8000/

mysql> describe proxys;
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | int(11)      | NO   | PRI | NULL    | auto_increment |
| ip         | varchar(16)  | NO   |     | NULL    |                |
| port       | int(11)      | NO   |     | NULL    |                |
| types      | int(11)      | NO   |     | NULL    |                |
| protocol   | int(11)      | NO   |     | NULL    |                |
| country    | varchar(100) | NO   |     | NULL    |                |
| area       | varchar(100) | NO   |     | NULL    |                |
| updatetime | datetime     | YES  |     | NULL    |                |
| speed      | decimal(5,2) | NO   |     | NULL    |                |
| score      | int(11)      | NO   |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
10 rows in set (0.02 sec)

mysql> select * from proxys;
Empty set (0.00 sec)

**Comment by qiyeboy** [comment]
这个py3版本bug，已成功修复 @bifeng

**Comment by bifeng** [comment]
太爽啦啦啦！已解决！
