### ISSUE TITLE
试用一下, 感觉不错. 有个小建议

### ISSUE THREAD

**Issue by viponedream** [qiyeboy/IPProxyPool#30]
requests.get( r'http://127.0.0.1:8000/?types=0&count=1&country=中国' )
原来是这样获取代理的.

这样返回来的每次都是一样的,
建议随机返回比较好.

最好每次都不同
有带评分的就随机返回该评分的IP,  否则就随机返回数据库中的任意IP

**Comment by viponedream** [comment]
1, 发现扫出来的代理IP, 没办法打开百度网站?
2, 刚才重启之后,发现数据库坏了, 程序可以判断数据库出故障之后, 干脆删除了重新建. 不要用原先的.

**Comment by qiyeboy** [comment]
@viponedream 不推荐随机返回，还是按照这种规则，不过你可以使用random方法随机选取作为代理

**Comment by qiyeboy** [comment]
@viponedream 你试试访问https://www.baidu.com

**Comment by viponedream** [comment]
问题是有点麻烦.
采集来的是ｈｔｔｐ代理．　　我手工把这个代理加到浏览器上去，　　确实没办法访问　百度的网站，　但是１６３．ｃｏｍ　就可以访问，　只是不太正常．

**Comment by qiyeboy** [comment]
最近会把检测ip的方式加上去 @viponedream

**Comment by viponedream** [comment]
发现问题了.
原来百度要使用 https的代理才行.
但是我看了一下数据库中,采集回来的全部是 http的,所以全部不能用.
建议采集的时候可以选择只采集  https的或者优先采集 https的

**Comment by qiyeboy** [comment]
@viponedream 不是全不能用吧，只是我默认将类型写为了0，之前类型检测的网站挂了，所以这段代码就删除了，之后会加上ip类型检测

**Comment by viponedream** [comment]
谢谢.
可以多设一个参数,  只要采集 https 的就行. 
判断方法可以去连百度,  能够连上百度的就是 https的.
