### ISSUE TITLE
IPProxyPool原理？一个小时还没过去，ip数量也大于minnum，为什么又自动爬取新的ip?

### ISSUE THREAD

**Issue by bifeng** [qiyeboy/IPProxyPool#31]
使用的还是python3
这里的config.py默认配置：
每一个小时检测一次
有效ip数据量至少40

第一次爬虫结果，获得167个有效ip，一个小时还没过去，又启动爬虫了：
![image](https://cloud.githubusercontent.com/assets/8215563/21375487/c71c4c6c-c768-11e6-9e93-8828734d2e22.png)

在这一个小时内，难道又在167个有效ip中不断进行测试？

**Comment by bifeng** [comment]
右键点了一下，之前显示的Success ip num:167,...  变成了：
127.0.0.1：51363 -- [....] ....
......
为什么？难道有效代理ip从167降到了8个？

**Comment by qiyeboy** [comment]
![ip](https://cloud.githubusercontent.com/assets/8142734/21376351/3a3a0d6e-c76f-11e6-9409-589bb6fa1f8f.png)

**Comment by bifeng** [comment]
能否解释一下，为什么没有到一个小时，为什么有效ip数量会发生变化？
![image](https://cloud.githubusercontent.com/assets/8215563/21377182/07a0ffcc-c777-11e6-9e03-f82ee5effb9b.png)

**Comment by qiyeboy** [comment]
每次启动程序，会首先检测数据库中 的ip是否有效

**Comment by qiyeboy** [comment]
如果ip数量在规定范围内，则等待一小时，然后再检测数据库中的ip有效性，直到小于规定数量才进行爬取 @bifeng

**Comment by bifeng** [comment]
代理ip失效时间不确定？在“等待一小时”的时间段内，有效的ip也可能会失效，该怎么办呢？只能缩短等待时间了？

**Comment by qiyeboy** [comment]
一般前20个ip比较稳定，不建议缩短等待时间，时间过短会容易被屏蔽

**Comment by bifeng** [comment]
提供代理的网站也会屏蔽？
