### ISSUE TITLE
建议一次验证失败不立即删除，建议加入ip添加的时间

### ISSUE THREAD

**Issue by greyhu** [qiyeboy/IPProxyPool#32]
1、除现有的评分外，希望可以得知IP存活时间用来更好的评估优质ip。
2、验证已有IP时，不可用的ip可以只标记不删除，添加失败次数，减扣评分（非线性的），评分过低再删除

**Comment by Petelin** [comment]
我觉得一个加分接口很有必要,找到一个可用的ip之后,很希望下次还用他.

**Comment by greyhu** [comment]
加分还是依赖项目内部的自动检查比较好吧？尽量和应用项目隔离。
删除接口是迫不得已，不删除会影响继续使用。不过这个删除也可以像建议那样只是标记，和验证失败等同处理。

**Comment by qiyeboy** [comment]
我需要评估一下这些ip的稳定性，大家有想法希望能提交pr，一起维护 @greyhu @Petelin
