### ISSUE TITLE
你好，验证IP的时候为什么要使用多进程+协程

### ISSUE THREAD

**Issue by planb3** [qiyeboy/IPProxyPool#35]
之前已经关注你了，新年快乐！
有个关于多进程+协程 的疑问？
因为我看教程都说，使用多进程的场景是：计算型密集型的程序才会用，进程可以真正使用多核。
线程：可以处理IO密集型的，去等待。
协程：也是事件驱动，适合解决等待的问题
是不是 多线程+协程，更适合呢。小白的浅见。。。。

**Comment by qiyeboy** [comment]
你看一下这篇博文，会加深你的理解http://blog.csdn.net/lambert310/article/details/51162634 @planb3
