### ISSUE TITLE
IP type 的问题

### ISSUE THREAD

**Issue by owlscowl** [qiyeboy/IPProxyPool#42]
用“http://httpbin.org/ip"检验高匿性，发现types=0的IP 仍有不少能看到自己的origin。请问这是validation的问题吗？另外，我输入types=1 或types=2，没有任何IP显示。

**Comment by qiyeboy** [comment]
我输入types=1 或types=2，没有任何IP显示,,说明没有这样的ip可用，用“http://httpbin.org/ip"检验高匿性，发现types=0的IP 仍有不少能看到自己的origin，希望可以给出这些ip是什么 @owlscowl

**Comment by owlscowl** [comment]
谢谢回复！比如这个ip 61.152.81.193:9100 , 在数据中的type为0（高匿），但是用http://httpbin.org/ip还是能查到origin

**Comment by qiyeboy** [comment]
61.152.81.193:9100这个ip对https代理是高匿的，对于http访问时透明的，访问时请加上protocol参数的限制，而且高匿ip对爬虫才有意义，所以之后的开发仅仅保留高匿ip

**Comment by qiyeboy** [comment]
@owlscowl

**Comment by owlscowl** [comment]
我明白了，谢谢您的及时回复！
