### ISSUE TITLE
python3: Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE

### ISSUE THREAD

**Issue by bifeng** [qiyeboy/IPProxyPool#43]
![image](https://cloud.githubusercontent.com/assets/8215563/21947916/ba0de45a-da22-11e6-930e-e5f791e693b1.png)

**Comment by bifeng** [comment]
如何消除掉这个warning?

**Comment by qiyeboy** [comment]
请问影响程序运行吗 @bifeng

**Comment by bifeng** [comment]
@qiyeboy
这倒没影响，数据存进去了，我是用您最近更新后的版本才出现的这个警告信息，之前的版本没有这个问题。
mysql 版本 5.7.11-log. 
在命令行下运行python IPProxy.py就会出现这个警告信息。

**Comment by qiyeboy** [comment]
这是sqlalchemy 的问题，我暂时不知道怎么解决，如果你找到解决办法，请告诉我一声 @bifeng

**Comment by Petelin** [comment]
mysql 建表的时候格式不对, 你改成utf-8 @bifeng

**Comment by hklliang** [comment]
Maybe it is a bug of mysqlclient or MySQL-python,Use pymysql and create_engine like this 'mysql+pymysql://root:123456@localhost/data?charset=utf8'

**Comment by EruDev** [comment]
我也遇到这个问题了 加上编码还是报错 
这是为什么

**Comment by JoffreyN** [comment]
D:\Program Files\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 518")
-------------------------------------------------------------------------------------------------------------------
同样的问题，但是我别的程序使用pymysql就没这个
