### ISSUE TITLE
很多僵死进程

### ISSUE THREAD

**Issue by zyq001** [qiyeboy/IPProxyPool#44]
hi，

      对python和gevent不太熟，运行工程会产生很多僵死进程，不知什么情况，好像mutiprocess也遇到这个问题，这对python来说是正常的吗？
       为了能及时打印出日志 nohup python -u 运行的。

操作系统：CentOS Linux release 7.2.1511
python：2.7.5

![image](https://cloud.githubusercontent.com/assets/7960619/22063451/e322cac8-ddb9-11e6-93dc-4a12f26eb756.png)

**Comment by qiyeboy** [comment]
我尝试重现一下，还有你运行了多长时间

**Comment by qiyeboy** [comment]
@zyq001

**Comment by zyq001** [comment]
应该是每次爬的时候都会产生多个僵死进程，在机器上第一次运行

**Comment by qiyeboy** [comment]
我不是在docker中运行的，直接在windows系统中运行，没有还原这种情况 @zyq001

**Comment by zyq001** [comment]
不是通过docker运行的，
![image](https://cloud.githubusercontent.com/assets/7960619/22920086/3a1c303e-f2ce-11e6-9371-5588749f062b.png)
可以通过查看进程树看到是倒数第二个进程产生
![image](https://cloud.githubusercontent.com/assets/7960619/22920158/91637014-f2ce-11e6-898a-131fb41020b2.png)
@qiyeboy @light4
