### ISSUE TITLE
数据存疑

### ISSUE THREAD

**Issue by fancoo** [qiyeboy/IPProxyPool#5]
因为我也做了一个，想了解下你抓的是哪几个网站呢，以及，数据量多大，有多少是死的数据啊

**Comment by Leibnizhu** [comment]
config.py里面就能看到

**Comment by fancoo** [comment]
网站种类好像比我的少，想了解最后抓完可用的ip的量有多大呢？

**Comment by qiyeboy** [comment]
@fancoo 可以提交更多的代理网址给我，我添加到项目中，现在能抓到20000个ip左右，可以实际能用的只有60左右

**Comment by fancoo** [comment]
我的名为"Proxy"的项目readme中有介绍几个网站的，我抓下来对ip进行score之后，长期稳定低延时的ip的比你大挺多的，你不用看我代码（比你的渣。。），用用数据源就行

**Comment by qiyeboy** [comment]
嗯呢，在下次更新，我把你的github添加说明文件中，表示感谢 @fancoo

**Comment by Leibnizhu** [comment]
@qiyeboy 补充一个http://proxy.mimvp.com/free.php?proxy=in_hp

**Comment by qiyeboy** [comment]
已经更新了，大家可以使用

**Comment by fancoo** [comment]
找了一圈没看到评分机制方面的代码，楼主方便介绍一下你的打分公式吗

**Comment by qiyeboy** [comment]
其实很简单，每一个小时检测一次，ip还能用， score就+1

**Comment by qiyeboy** [comment]
@fancoo

**Comment by fancoo** [comment]
thx
