### ISSUE TITLE
配置到mysql，但好像存不进去？？

### ISSUE THREAD

**Issue by breadying** [qiyeboy/IPProxyPool#54]
sqlite的能行，然后想更换到mysql，能够新建表，但是数据存不进去

IPProxyPool----->>>>>>>>beginning
http://0.0.0.0:8000/
IPProxyPool----->>>>>>>>db exists ip:0
IPProxyPool----->>>>>>>>now ip num < MINNUM,start crawling...
IProxyPool----->>>>>>>>Success ip num :0,Fail ip num:2986

后来有试过打印出proxy，显示none

求大神指导！

**Comment by caizh666** [comment]
我能存，你哪配置错了吧。

**Comment by chuihero** [comment]
碰到这个问题，解决了。
检查一下表的编码，用“show create table proxy”看一下是否默认编码和列字段的编码不是utf8。然后把表的默认编码和列字段编码都改为utf8。
貌似sqlalchemy在创建表时没有考虑编码方式，即使连接字符串加上charset=utf8。
