### ISSUE TITLE
什么都没改，可能是我哪里配置错了，错误如下

### ISSUE THREAD

**Issue by jingkonglanxing** [qiyeboy/IPProxyPool#58]
ubuntu@ubuntu:/IPProxyPool$ sudo python IPProxy.py 
Traceback (most recent call last):
  File "IPProxy.py", line 4, in <module>
    from api.apiServer import start_api_server
  File "/IPProxyPool/api/apiServer.py", line 9, in <module>
    from db.DataStore import sqlhelper
  File "/IPProxyPool/db/DataStore.py", line 15, in <module>
    raise Con_DB_Fail
util.exception.Con_DB_Fail: <exception str() failed>

web.py源码安装
我不太清楚哪里错了，环境python3.5  是不是我哪里没弄好  邮箱：alongrichangjing@163.com
期望看到你的邮件，先谢谢了

**Comment by qiyeboy** [comment]
应该是sqlite没有安装或者安装有问题 @jingkonglanxing

**Comment by jingkonglanxing** [comment]
best wishes to you 
I kown what happened to me
I  run it in ubuntu ,but I run it in user ubuntu ，it errors
when I run it in root mode ,everythin is ok
