### ISSUE TITLE
py3下出现问题

### ISSUE THREAD

**Issue by cckiss** [qiyeboy/IPProxyPool#6]
Traceback (most recent call last):
  File "IPProxys/IPProxys.py", line 2, in <module>
    import BaseHTTPServer
ImportError: No module named 'BaseHTTPServer'

BaseHTTPServer 应该是2下面的吧，有什么能替代的吗？

**Comment by qiyeboy** [comment]
目前是适用于2.7.x,py3不适用，本周末我会添加上对py3的支持，可以等我更新

**Comment by qiyeboy** [comment]
@cckiss

**Comment by cckiss** [comment]
好的，我对这个项目有点兴趣，支持下
@qiyeboy

**Comment by cloudchou** [comment]
支持3.0了吗?

**Comment by qiyeboy** [comment]
还没重构完，大家希望添加的功能有点多，也就本周的事情了 @cloudchou

**Comment by cloudchou** [comment]
@qiyeboy 好的收到

**Comment by Cloudzhao230** [comment]
支持作者也做也好，现在Python3越来越好，希望能支持Python3

**Comment by logicxin** [comment]
python3.4同样出现问题：ImportError: No module named 'BaseHTTPServer'
期待作者的更新~ 辛苦~~

**Comment by qiyeboy** [comment]
已经更新了，大家可以使用
