### ISSUE TITLE
在哪里可以改变测试URL的链接，就是我想得到对特定网站有效的ip地址。

### ISSUE THREAD

**Issue by hklliang** [qiyeboy/IPProxyPool#72]
![image](https://cloud.githubusercontent.com/assets/24997125/23978468/1d9cd256-0a2f-11e7-9ff8-6c282ee83a11.png)
TEST_URL = 'http://ip.chinaz.com/getip.aspx'
TEST_IP = 'http://httpbin.org/ip'
TEST_HTTP_HEADER = 'http://httpbin.org/get'
TEST_HTTPS_HEADER = 'https://httpbin.org/get'
# #添加的检测关键字，修复测试的代理是否能真正的访问到目的网址
# TEST_KEY = '站长工具'
TEST_PROXY = 'http://www.stilllistener.com/checkpoint1/test11/'

**Comment by agua19940824** [comment]
同问

**Comment by qiyeboy** [comment]
本周进行更新
