### ISSUE TITLE
连接数据库失败？

### ISSUE THREAD

**Issue by zhengooxingoo** [qiyeboy/IPProxyPool#74]
使用XAMPP下的mysql，为什么
第一步：首先安装MySQL数据库并启动
第二步：安装MySQLdb或者pymysql(推荐)
第三步：在config.py文件中配置DB_CONFIG。
完成了这三步，可仍显示DB_CONNECT_STRING:%s--连接数据库失败？
求各路英雄不吝赐教~~

**Comment by qiyeboy** [comment]
你没有在mysql中建数据库
