### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by Leibnizhu** [qiyeboy/IPProxyPool#8]
部署在Ubuntu 14.04 Server版后，第二天开始大量报错：
'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
查了下应该是编码问题，系统LANG环境变量目前是zh_CN.UTF-8，请问如何解决？

**Comment by qiyeboy** [comment]
已经使用chardet探测网页编码，如果是其他编码问题，log界面截一下图

**Comment by Leibnizhu** [comment]
截取了控制台输出的一小段，还有很多，都是差不多的：
1.207.19.102 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in ranHtmlDownLoader 2016-11-26 11:28:24 INFO 18 downloading url: http://m.66ip.cn/areaindex_22/3.html
ge(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.207.19.102 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
[<Element tr at 0x7f1149b7da28>, <Element tr at 0x7f1149b7dc20>, <Element tr at 0x7f11492f7680>, <Element tr at 0x7f1149ba1a70>, <Element tr at 0x7f1149ba1cf8>, <Element tr at 0x7f114a49f050>, <Element tr at 0x7f11492d95f0>, <Element tr at 0x7f11492d9b48>, <Element tr at 0x7f11492d9950>, <Element tr at 0x7f1149333200>, <Element tr at 0x7f1149333710>, <Element tr at 0x7f1149333098>, <Element tr at 0x7f1149333bd8>, <Element tr at 0x7f1149333440>, <Element tr at 0x7f1149333a28>, <Element tr at 0x7f1149333950>, <Element tr at 0x7f11493337e8>, <Element tr at 0x7f1149333d88>, <Element tr at 0x7f11493336c8>, <Element tr at 0x7f1149333050>, <Element tr at 0x7f1149333680>, <Element tr at 0x7f1149333c20>, <Element tr at 0x7f1149333ea8>, <Element tr at 0x7f1149333b48>, <Element tr at 0x7f1149333f80>, <Element tr at 0x7f1149333cb0>, <Element tr at 0x7f11493333b0>, <Element tr at 0x7f1149333cf8>, <Element tr at 0x7f1149333b90>, <Element tr at 0x7f11493331b8>, <Element tr at 0x7f11493330e0>, <Element tr at 0x7f11493339e0>, <Element tr at 0x7f11493333f8>, <Element tr at 0x7f1149333ef0>, <Element tr at 0x7f11493332d8>, <Element tr at 0x7f1149333170>, <Element tr at 0x7f1149333b00>, <Element tr at 0x7f11493338c0>, <Element tr at 0x7f1149333830>, <Element tr at 0x7f1149333758>, <Element tr at 0x7f1149333e18>, <Element tr at 0x7f1149333518>, <Element tr at 0x7f1149333248>, <Element tr at 0x7f11493334d0>, <Element tr at 0x7f1149333c68>, <Element tr at 0x7f1149333d40>, <Element tr at 0x7f1149333998>, <Element tr at 0x7f1149333638>, <Element tr at 0x7f1149333290>, <Element tr at 0x7f1149333488>, <Element tr at 0x7f11493337a0>, <Element tr at 0x7f1149333368>, <Element tr at 0x7f1149333320>, <Element tr at 0x7f1149333e60>, <Element tr at 0x7f1149337638>, <Element tr at 0x7f1149337908>, <Element tr at 0x7f1149b473b0>, <Element tr at 0x7f1149b47710>, <Element tr at 0x7f1149b54f38>, <Element tr at 0x7f1149b54d88>, <Element tr at 0x7f1149b54e60>, <Element tr at 0x7f1149b542d8>, <Element tr at 0x7f1149b54fc8>, <Element tr at 0x7f1149b54f80>, <Element tr at 0x7f1149b54ab8>, <Element tr at 0x7f1149b54ef0>, <Element tr at 0x7f1149b54560>, <Element tr at 0x7f1149b54b00>, <Element tr at 0x7f1149b54050>, <Element tr at 0x7f1149b54c20>, <Element tr at 0x7f1149b54290>, <Element tr at 0x7f1149b54098>, <Element tr at 0x7f1149b54d40>, <Element tr at 0x7f1149b541b8>, <Element tr at 0x7f1149b54488>, <Element tr at 0x7f1149b54128>, <Element tr at 0x7f1149b54320>, <Element tr at 0x7f1149b54440>, <Element tr at 0x7f1149b54368>, <Element tr at 0x7f1149b54200>, <Element tr at 0x7f1149b54b90>, <Element tr at 0x7f1149b54638>, <Element tr at 0x7f11493134d0>, <Element tr at 0x7f1149bb8e18>, <Element tr at 0x7f1149bb8f38>, <Element tr at 0x7f1149bb8878>, <Element tr at 0x7f1149bb8ef0>, <Element tr at 0x7f1149bb8d40>, <Element tr at 0x7f1149bb8c20>, <Element tr at 0x7f1149bb8638>, <Element tr at 0x7f1149bb8128>, <Element tr at 0x7f1149bb8488>, <Element tr at 0x7f1149bb8c68>, <Element tr at 0x7f1149bb87a0>]
220.171.227.27 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
220.171.227.27 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.120.2.138 3128 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.207.84.120 3128 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.120.2.138 3128 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.207.84.120 3128 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
119.1.63.20 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
220.172.226.74 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
119.1.63.20 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
220.172.226.74 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
106.32.14.193 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.120.40.62 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
106.32.14.193 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.120.40.62 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.49.84.89 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.49.84.89 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.207.5.58 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.120.126.69 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.207.5.58 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.120.126.69 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.207.62.194 3128 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.120.2.138 3128 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.207.62.194 3128 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.120.2.138 3128 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.49.234.0 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
1.49.234.0 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.124.105.62 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.124.105.62 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
220.171.243.31 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
218.86.128.12 8118 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
220.171.243.31 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
220.171.243.31 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.124.56.224 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
220.171.243.31 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.124.56.224 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
111.124.56.224 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by Leibnizhu** [comment]
用grep看了最近出现问题的20个地址，都是http://m.66ip.cn/
cat nohup.out| grep -B 3 "can't encode characters in position" | grep 'downloading url'| tail -20
124.119.217.110 8998 'ascii' codec can't encode characters in position 0-3: ordinal not in rHtmlDownLoader 2016-11-26 12:57:05 INFO 18 downloading url: http://m.66ip.cn/areaindex_32/8.html
59.75.128.205 8HtmlDownLoader 2016-11-26 12:57:05 INFO 18 downloading url: http://m.66ip.cn/areaindex_32/9.html
123.80.95.208 8123 'ascii' codec can't encode characters in position 0-3: ordinal not in range(1HtmlDownLoader 2016-11-26 12:57:05 INFO 18 downloading url: http://m.66ip.cn/areaindex_33/1.html
202HtmlDownLoader 2016-11-26 12:57:05 INFO 18 downloading url: http://m.66ip.cn/areaindex_33/2.html
180.178.45.186 3128 'ascii'HtmlDownLoader 2016-11-26 12:57:05 INFO 18 downloading url: http://m.66ip.cn/areaindex_33/3.html
223.197.56.102 80 'ascii' codec can't encode characters in position 0-3: ordiHtmlDownLoader 2016-11-26 12:57:06 INFO 18 downloading url: http://m.66ip.cn/areaindex_33/4.html
123.203.191.162 8080 'ascii' codec can't encode characters in position 0-3: ordHtmlDownLoader 2016-11-26 12:57:06 INFO 18 downloading url: http://m.66ip.cn/areaindex_33/5.html
202.130.104.236 8080 'ascii' codec canHtmlDownLoader 2016-11-26 12:57:06 INFO 18 downloading url: http://m.66ip.cn/areaindex_33/6.html
203.161.4.71 9090 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)HtmlDownLoader 2016-11-26 12:57:07 INFO 18 downloading url: http://m.66ip.cn/areaindex_33/7.html
61.93.131.116 8998 'ascii' codec can't encode charactersHtmlDownLoader 2016-11-26 12:57:07 INFO 18 downloading url: http://m.66ip.cn/areaindex_33/8.html
103.227.38.26 5050 'ascii' codec can't encode characters in position 0-3: ordinal not in range(1HtmlDownLoader 2016-11-26 12:57:07 INFO 18 downloading url: http://m.66ip.cn/areaindex_33/9.html
202.130.104.236 8080 'ascii' codec can't encode characters in positHtmlDownLoader 2016-11-26 12:57:08 INFO 18 downloading url: http://m.66ip.cn/areaindex_34/1.html
202.171.253.72 80 'ascii' codec can't encode characters in position 0-3: ordinaHtmlDownLoader 2016-11-26 12:57:08 INFO 18 downloading url: http://m.66ip.cn/areaindex_34/2.html
125.31.1.25 80 'HtmlDownLoader 2016-11-26 12:57:08 INFO 18 downloading url: http://m.66ip.cn/areaindex_34/3.html
125.31.1.25 80 'ascii' codec can't encode characters in position 0-3: ordinal not in range(12HtmlDownLoader 2016-11-26 12:57:08 INFO 18 downloading url: http://m.66ip.cn/areaindex_34/4.html
125.31.1.25 80 'ascii' codec can't encoHtmlDownLoader 2016-11-26 12:57:08 INFO 18 downloading url: http://m.66ip.cn/areaindex_34/5.html
125.31.1.25 80 'ascii' codec can't encode characters in position 0-3: ordinal nHtmlDownLoader 2016-11-26 12:57:09 INFO 18 downloading url: http://m.66ip.cn/areaindex_34/6.html
125.31.1.25 80 'ascii' codec can't encode characters in position HtmlDownLoader 2016-11-26 12:57:09 INFO 18 downloading url: http://m.66ip.cn/areaindex_34/7.html
202.171.253.72 80 'ascii' codec can't encode characters in position 0-3: ordinal not in range(12HtmlDownLoader 2016-11-26 12:57:09 INFO 18 downloading url: http://m.66ip.cn/areaindex_34/8.html
202.171.253.72 80 'ascii' codec can't encode characters in position 0-3: ordinal not in ranHtmlDownLoader 2016-11-26 12:57:09 INFO 18 downloading url: http://m.66ip.cn/areaindex_34/9.html

**Comment by qiyeboy** [comment]
我修复了一下，push上去了，你试试 @Leibnizhu

**Comment by Leibnizhu** [comment]
@qiyeboy，刚pull下来部署上去，还是一样的问题

**Comment by qiyeboy** [comment]
应该解决了@Leibnizhu 你试试吧

**Comment by Leibnizhu** [comment]
@qiyeboy 可以了，非常感谢。
另外我fork了这个项目，因个人需要给http 服务器加了一个删除代理的API，有没有必要加进来？

P.S. 这个爬虫扒回来的代理在python下用requests都能用，但是在浏览器中设置的话，只有FireFox能用，其他的浏览器设置了代理就会提示Access not allow，在Java中用HtmlUnit创建内置FireFox浏览器来通过这些代理访问也是只有部分可以用，很奇怪，所以我才加了这个删除的API，让我另一个Java项目去调用，删除一些经过Java HtmlUnit多次尝试无法使用的代理。

P.S.S. 懒得再开个issue了。

**Comment by qiyeboy** [comment]
嗯呢，可以，这个项目还不完善，最近我会进行整体重构，到时候会留出接口。

**Comment by qiyeboy** [comment]
@Leibnizhu

**Comment by qiyeboy** [comment]
已经更新了，大家可以使用
