### ISSUE TITLE
请问关于代理IP打分的问题

### ISSUE THREAD

**Issue by Wangzhijie2016** [qiyeboy/IPProxyPool#83]
假如说某IP当天测试不可用，分数 - 1  当前是9,那么下次再次测试时代理可用，那么分数是保持不变还是会 +1  保证分数为10的代理IP是高可用的？

**Comment by qiyeboy** [comment]
分数保持不变，说明文档中有

**Comment by Wangzhijie2016** [comment]
我建议测试可用的IP分值小于10的 +1 这样可以保证分值为10的均是高可用的
