### ISSUE TITLE
用redis做数据库时删除ip问题

### ISSUE THREAD

**Issue by agua19940824** [qiyeboy/IPProxyPool#84]
数据库用的是redis
安装Readme 里的介绍删除IP：http://127.0.0.1:8000/delete?ip=120.92.3.127 
我试了几次都不成功，都是返回0
后面加上端口参数就成功删除了：http://127.0.0.1:8000/delete?ip=120.92.3.127&port=8888
希望作者更新一下readme

**Comment by qiyeboy** [comment]
只是redis时出错吗？

**Comment by agua19940824** [comment]
之前用sqlite老出现数据库被锁的情况，我提了个isssue，不过你删了，所以就用了redis
用redis也不是出错，就是用ip去请求删除的时候，后面要带上一个port参数才能成功删除。。
其他数据库暂时还没用过。。

**Comment by qiyeboy** [comment]
sqlite并发性太差，不建议用。redis我修复一下
